---
title: "<strong>First steps of database design</strong>"
author: "INFO6540<br>Philippe Mongeon"
date: "2022-01-25"
output: 
  revealjs::revealjs_presentation:
    theme: simple
    highlight: pygments
    center: true
    self_contained: false
    reveal_plugins: ["chalkboard", "menu"]
    reveal_options:
      slideNumber: true
      previewLinks: true
      chalkboard:
        theme: default
        toggleNotesButton: true
      menu:
        side: right
---

# Plan

-   Database mission statement

-   Database objectives statement

-   Subjects

-   Subject attributes

-   Database rules

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(kableExtra)
```

```{=html}
<style>
    .reveal section img { 
        background:none; 
        border:none; 
        box-shadow:none; 
</style>
```
# Mission statement

## **What is a mission statement?**

The database mission statement states its purpose. It answers the questions "why do we need a database?"

## **Why do we need a mission statement?**

The mission statement establishes the focus of the database and will acts as a guide during the entire design process.

## **What is a good mission statement?**

::: {style="text-align:left"}
A good mission statement:

-   is clear

-   is concise

-   does not describe specific tasks that the users of the database will perform.
:::

## **Mission statement examples**

::: {style="text-align: left"}
*The purpose of the gummybox_sales database is to manage the data needed by the sales department to attend to the customers' sweet tooth.*

*The pupose of the Dalhousie University awards database is to support the operations of the awards committee and the celebration of student talents.*
:::

## **Extra tips for writing your mission statements**

::: {style="text-align: left"}
-   Do not overthink it

-   Keep it simple

-   Start with "*The purpose of the name of organization and/or organizational unit database is..."*
:::

# Objective statements

## What are objective statements?

The objectives relate to the tasks or needs of people inside the organization (e.g., employees) or outside the organization (e.g., clients or users). Here are the objectives of the *gummybox_sales* database

## **Why do we need objective statements?**

::: {style="text-align:left"}
Objectives:

-   Translate the mission (the why) into actions (the what).

-   Clarify what tasks the database needs to support.

-   Help the database designer identify the data needs.
:::

## **What are a good objective statements?**

::: {style="text-align:left"}
Good objective statements:

-   Are **clear** and **concise**, and non-ambiguous.

-   Contain a **single** task.

-   Do not mention **how** a task is performed.
:::

## **Example of objective statements**

::: {style="text-align:left"}
The objectives of the gummybox_sales database are:

-   Maintain customer information.
-   Keep track of orders.
-   Maintain information on gummies.
-   Maintain information on gummy assortments.
-   Collect product reviews.
:::

## **Extra tips for writing objective statements**

::: {style="text-align:left"}
-   Do not overthink it

-   Keep them simple

-   Keep them short (sometimes three words are enough)
:::

# Database subjects

## **What are database subjects?**

Think of your database as a simplified representation of the universe.

Subjects are the things (**objects** and **events**) that exist in that universe.

## **Why do we need to identify database subjects?**

::: {style="text-align:left"}
-   Subjects will become tables in the database. They are the central piece.

-   A well-defined list of subjects ensures that we don't forget anything or include things that are not necessary in our database design.
:::

## **How to identify database subjects?**

Ask yourself: *What **kinds** of things exist in my universe?*

## **Example of database subjects**

products, clients, employees, tansactions, orders, invoices, tweets, emails, courses, pets, furniture, equipment, instructors, locations, movies, books, stores, artists, etc.

## **Extra tips for identifying database subjects**

::: {style="text-align:left"}
-   Don't be too specific (e.g., undergraduate students and graduate students)

-   Don't be to generic (e.g., people).

Your subject are:

-   too generic if they have subcategories with different attributes (see next slides).

-   too specific if different subjects have the same attributes.
:::

# Subject attributes

## **What are subject attributes?**

The attributes are the characteristics that define your subjects in the context of your restricted database universe.

## **Why do we need to identify subject attributes?**

::: {style="text-align:left"}
-   They are the second central piece of your database. They will be columns in your tables.

<!-- -->

-   A well-defined list of attributes ensures that we don't forget anything or include things that are not necessary in our database design.
:::

## **How do we identify subject attributes?**

For each **subject**, ask yourself: *What **characteristics** definethat subject in the limited universe of my database?*

## **Example of subject attributes**

+-----------+-----------------------------------------------------------------------------------+
| Subjects  | Attributes                                                                        |
+===========+===================================================================================+
| Gummy     | name, description, consistency, colour, flavour, flavour_type, price, etc.        |
+-----------+-----------------------------------------------------------------------------------+
| Customer  | first name, last name, email, phone number, address                               |
+-----------+-----------------------------------------------------------------------------------+
| Address   | street name, civic number, apartment number, city, province, country, postal code |
+-----------+-----------------------------------------------------------------------------------+
| Order     | Customer, product, amount of product, delivery address, date                      |
+-----------+-----------------------------------------------------------------------------------+

## **What are good subject attribute?**

-   They are necessary to achieve the database objectives.

-   They are related to the subject (e.g., The "cat" subject could have a "breed" attribute, but "cat breed" should not be an attribute of the person who owns that cat).

-   They are non-ambiguous.

-   They are atomic (a single attribute can't be divided in multiple attributes).

# Database rules

## **What are database rules?**

Rules are statements that define or constrain the possibilities of your database.

## **Why kind of rules exist?**

-   Rules that specify **the set** of values a attribute can have. (e.g., the country attribute is limited to the set of existing countries).

    -   For this course, you don't have to specify the set of values itself (you don't need a list of countries).

-   Rules that specify whether or not an attribute can have multiple values for the same entity (e.g. can a single gummy have multiple flavours?).

    -   For this course, it is sufficient to consider if an entity can have multiple values or not. It is not necessary to define the number of values that an attribute can have.

## **How to identify database rules?**

::: {style="text-align:left"}
For each attribute, ask yourself:

1.  Can this attribute take multiple value for a single entity?
2.  Is there a limited range of values for this attribute?
:::

## **Example of database rules**

| Subject  | Attribute    | Rule                                      |
|----------|--------------|-------------------------------------------|
| Gummy    | Flavour      | A gummy can have multiple flavor          |
| Gummy    | Flavour type | A gummy can have multiple flavour type    |
| Gummy    | Flavour type | Is limited to a set of five flavour types |
| Gummy    | Colour       | A gummy can have multiple colours         |
| Customer | Address      | A customer can have multiple addresses    |

## **Extra tips for identifying database rules**

::: {style="text-align:left"}
-   Use rules parcimoniously
-   Put more attention on values that scefify whether or not a single entity can have multiple values for the same attribute. Those have more implications for database designs.
:::
